Add reroll functionality to standard rolls.
wRAR/supybot-plugin-Dicebot pull request #2
Opened 2018-02-18 19:05 UTC by ashein

This should add the "r" or "r + number" suffix notation to standard dice rolls so that they would reroll silently if at or below the given threshold (defaults to one). This modifies standard roll routines, but doesn't seem to break anything so far.

2018-02-23 16:10 UTC, wRAR requested changes

2018-02-23 16:10 UTC, wRAR commented on Dicebot/plugin.py
> +        results = [ ]
лишнее

2018-02-23 16:10 UTC, wRAR commented on Dicebot/plugin.py
> +                reroll = opts.group('reroll') and int(opts.group('reroll')) or 0
`int(opts.group('reroll') or 0)`

2018-02-23 16:10 UTC, wRAR commented on Dicebot/plugin.py
> +
лишнее

2018-02-24 19:53 UTC, ashein commented
Not sure how to mark the lines where changes were needed as "resolved".

2018-02-25 13:51 UTC, wRAR requested changes

2018-02-25 13:51 UTC, wRAR commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
весь этот коммит не нужен

2018-03-06 16:45 UTC, closed without merging